# Generated by Django 5.2.4 on 2025-08-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_progresslogs_delete_progresslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressLogs',
        ),
    ]
