# Generated by Django 5.2.4 on 2025-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_progresslogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
